apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app:  nginx # this should match the labels in the deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
